### PR TITLE
1046 | Raised event for Link creation.

### PR DESCRIPTION
**Pull request by angshu**
Refactored:
- moved /user/auth/ APIs to UserAuthController
- replaced and removed GatewayResponse, and replaced from in.projecteka.library

### CODE REVIEW

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/RequesterType.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthentication.java  2
- consent/src/main/java/in/projecteka/consentmanager/clients/UserAuthServiceClient.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthController.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/IdentifierUtils.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthInitAction.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/IdentifierType.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/LinkEventPublisher.java  1
         

Clones added
============
- consent/src/main/java/in/projecteka/consentmanager/clients/UserAuthServiceClient.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6314577&bid=20530767)

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/clients/UserAuthServiceClient.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/RequesterType.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthentication.java  2
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/IdentifierType.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/LinkEventPublisher.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/IdentifierUtils.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthController.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthInitAction.java  1
         

Clones added
============
- consent/src/main/java/in/projecteka/consentmanager/clients/UserAuthServiceClient.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6314577&bid=20530767)

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthController.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/RequesterType.java  1
- consent/src/main/java/in/projecteka/consentmanager/clients/UserAuthServiceClient.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/IdentifierType.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/LinkEventPublisher.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/Constants.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthentication.java  2
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/IdentifierUtils.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthInitAction.java  1
         

Clones added
============
- consent/src/main/java/in/projecteka/consentmanager/clients/UserAuthServiceClient.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6314577&bid=20530767)

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthentication.java  2
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/IdentifierUtils.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/IdentifierType.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/model/RequesterType.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/Constants.java  1
- consent/src/main/java/in/projecteka/consentmanager/clients/UserAuthServiceClient.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthController.java  1
- consent/src/main/java/in/projecteka/consentmanager/userauth/UserAuthInitAction.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/LinkEventPublisher.java  1
         

Clones added
============
- consent/src/main/java/in/projecteka/consentmanager/clients/UserAuthServiceClient.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6314577&bid=20530767)

**Review by Nexengineer — APPROVED** [review]

**Pull request merged**
