### PR TITLE
Remove user service

### PR DESCRIPTION
**Pull request by ganesanarun**

### CODE REVIEW

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierType.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierUtils.java  1
         

Complexity decreasing per file
==============================
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
         

Clones removed
==============
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
+ consent/src/test/java/in/projecteka/consentmanager/SecurityConfigurationTest.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6068794&bid=19874010)

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierType.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierUtils.java  1
         

Complexity decreasing per file
==============================
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
         

Clones removed
==============
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
+ consent/src/test/java/in/projecteka/consentmanager/SecurityConfigurationTest.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6068794&bid=19874010)

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierType.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierUtils.java  1
         

Complexity decreasing per file
==============================
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
         

Clones removed
==============
+ consent/src/test/java/in/projecteka/consentmanager/SecurityConfigurationTest.java  -1
+ user/src/main/java/in/projecteka/user/filters/YOBFilter.java  -1
+ user/src/main/java/in/projecteka/user/TokenService.java  -1
+ user/src/main/java/in/projecteka/user/SecurityConfiguration.java  -1
+ user/src/main/java/in/projecteka/user/filters/ABPMJAYIdFilter.java  -1
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
+ user/src/main/java/in/projecteka/user/LockedUserService.java  -1
+ user/src/main/java/in/projecteka/user/OtpAttemptRepository.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6068794&bid=19874010)

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierUtils.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierType.java  1
         

Complexity decreasing per file
==============================
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
         

Clones removed
==============
+ consent/src/test/java/in/projecteka/consentmanager/SecurityConfigurationTest.java  -1
+ user/src/main/java/in/projecteka/user/OtpAttemptRepository.java  -1
+ user/src/main/java/in/projecteka/user/filters/YOBFilter.java  -1
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
+ user/src/main/java/in/projecteka/user/filters/ABPMJAYIdFilter.java  -1
+ user/src/main/java/in/projecteka/user/LockedUserService.java  -1
+ user/src/main/java/in/projecteka/user/TokenService.java  -1
+ user/src/main/java/in/projecteka/user/SecurityConfiguration.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6068794&bid=19874010)

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierUtils.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierType.java  1
         

Complexity decreasing per file
==============================
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
         

Clones removed
==============
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
+ user/src/main/java/in/projecteka/user/TokenService.java  -1
+ user/src/main/java/in/projecteka/user/SecurityConfiguration.java  -1
+ user/src/main/java/in/projecteka/user/OtpAttemptRepository.java  -1
+ consent/src/test/java/in/projecteka/consentmanager/dataflow/TestBuilders.java  -1
+ user/src/main/java/in/projecteka/user/filters/ABPMJAYIdFilter.java  -1
+ user/src/main/java/in/projecteka/user/filters/YOBFilter.java  -1
+ consent/src/test/java/in/projecteka/consentmanager/SecurityConfigurationTest.java  -1
+ user/src/main/java/in/projecteka/user/LockedUserService.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6068794&bid=19874010)

**Comment by ganesanarun** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierType.java  1
- consent/src/main/java/in/projecteka/consentmanager/link/hiplink/model/request/IdentifierUtils.java  1
         

Complexity decreasing per file
==============================
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
         

Clones removed
==============
+ consent/src/main/java/in/projecteka/consentmanager/SecurityConfiguration.java  -1
+ user/src/main/java/in/projecteka/user/OtpAttemptRepository.java  -1
+ user/src/main/java/in/projecteka/user/LockedUserService.java  -1
+ user/src/main/java/in/projecteka/user/SecurityConfiguration.java  -1
+ user/src/main/java/in/projecteka/user/TokenService.java  -1
+ user/src/main/java/in/projecteka/user/filters/ABPMJAYIdFilter.java  -1
+ user/src/main/java/in/projecteka/user/filters/YOBFilter.java  -1
+ consent/src/test/java/in/projecteka/consentmanager/dataflow/TestBuilders.java  -1
+ consent/src/test/java/in/projecteka/consentmanager/SecurityConfigurationTest.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/ProjectEKA/consent-manager/pullRequest?prid=6068794&bid=19874010)

**Review by leelanakka — APPROVED** [review]

**Pull request merged**
